Warning: Deprecated pattern style '/Users/bbianco/code/rivet/example/**' in /Users/bbianco/code/rivet/.rubocop.yml. Change to '/Users/bbianco/code/rivet/example/**/*'.
Warning: Deprecated pattern style '/Users/bbianco/code/rivet/example/**' in /Users/bbianco/code/rivet/.rubocop.yml. Change to '/Users/bbianco/code/rivet/example/**/*'.



AllCops:
  Exclude:
    - autoscale/**/*
    - example/**/*
    - example/autoscale/**/*

Eval:
  Enabled: false

LineLength:
  Enabled: false

HashSyntax:
  Enabled: false

MethodLength:
  Max: 25

